<%--flexberryautogenerated="false"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="NakladnayaE.aspx.cs" Inherits="IIS.Практикум.НакладнаяE" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
    <script type="text/javascript">
	$('#<%= ctrlЗаказ.ClientID %>').on('change', function (e, d) {
		$.ics.postBack('', '');
	});
</script>
</asp:Content>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass + " " +  Constants.EditFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass + " " + Constants.EditFormHeaderCssClass %>">Накладная</h2>
        <div class="<%= Constants.FormToolbarCssClass  + " " +  Constants.EditFormToolbarCssClass + " " + Constants.StickyCssClass %>">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="<%= Constants.FormControlsCssClass + " " + Constants.EditFormControlsCssClass %>">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlСтатусLabel" runat="server" Text="Статус" EnableViewState="False">
</asp:Label>
<asp:DropDownList ID="ctrlСтатус" CssClass="descTxt" runat="server">
	<asp:ListItem>Новая</asp:ListItem>
<asp:ListItem>Выписанная</asp:ListItem>
<asp:ListItem>Приостановленная</asp:ListItem>
<asp:ListItem>Готовая</asp:ListItem>
<asp:ListItem>Отгруженная</asp:ListItem>

</asp:DropDownList>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlДатаВремяОтгрузкиLabel" runat="server" Text="Дата время отгрузки" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlДатаВремяОтгрузки" CssClass="descTxt" runat="server"/>
</div>
<ac:DatePickerValidator ID="ctrlДатаВремяОтгрузкиDatePickerValidator" runat="server" ControlToValidate="ctrlДатаВремяОтгрузки" 
                        ErrorMessage="Введена некорректная дата: Дата время отгрузки." Text="*" 
                        EnableClientScript="true" ValidationGroup="savedoc" CssClass="validator-datePicker" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlСуммаLabel" runat="server" Text="Сумма" EnableViewState="False">
</asp:Label>
<ac:DecimalTextBox runat="server" CssClass="descTxt" ID="ctrlСумма">
</ac:DecimalTextBox>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlВесLabel" runat="server" Text="Вес" EnableViewState="False">
</asp:Label>
<ac:DecimalTextBox runat="server" CssClass="descTxt" ID="ctrlВес">
</ac:DecimalTextBox>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlПримечаниеLabel" runat="server" Text="Примечание" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlПримечание" runat="server">
</asp:TextBox>


</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlФИОПолучателяLabel" runat="server" Text="Ф и о получателя" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlФИОПолучателя" runat="server">
</asp:TextBox>


</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlНомерLabel" runat="server" Text="Номер" EnableViewState="False">
</asp:Label>
<ac:AlphaNumericTextBox CssClass="descTxt" ID="ctrlНомер" Type="Numeric" runat="server">
</ac:AlphaNumericTextBox>


</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlДатаЗаполненияLabel" runat="server" Text="Дата заполнения" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlДатаЗаполнения" CssClass="descTxt" runat="server"/>
</div>
<ac:DatePickerValidator ID="ctrlДатаЗаполненияDatePickerValidator" runat="server" ControlToValidate="ctrlДатаЗаполнения" 
                        ErrorMessage="Введена некорректная дата: Дата заполнения." Text="*" 
                        EnableClientScript="true" ValidationGroup="savedoc" CssClass="validator-datePicker" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlМатериальноОтветственноеЛицоLabel" runat="server" Text="Материально ответственное лицо" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlМатериальноОтветственноеЛицо" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlМатериальноОтветственноеЛицоRequiredFieldValidator" runat="server" ControlToValidate="ctrlМатериальноОтветственноеЛицо"
                            ErrorMessage="Не указано: МатериальноОтветственноеЛицо" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlЗаказLabel" runat="server" Text="Заказ" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlЗаказ" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlЗаказRequiredFieldValidator" runat="server" ControlToValidate="ctrlЗаказ"
                            ErrorMessage="Не указано: Заказ" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<asp:ScriptManager ID="ScriptManager1" runat="server" >
</asp:ScriptManager>

<div style="clear: left">
	<ac:AjaxGroupEdit CssClass="$PERCENTMW$descTxt" ID="ctrlЗаписьВНакладной" runat="server" ReadOnly="false" />
</div>
<br/>

</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
