<%--flexberryautogenerated="false"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="ZakazE.aspx.cs" Inherits="IIS.Практикум.ЗаказE" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ContentPlaceHolderID="ContentPlaceHolder0"  runat="server" >
	<script type="text/javascript">

        $(document).ready(function () {
            var lfName = '';
            var ordKeys = [];
            $('[id$=ctrlТовар]', '#<%=ctrlСтрокаЗаказа.ClientID%>').each(
                function () {
                    ordKeys.push($(this).val());
                });

            var changeLf = function () {
                $.ajax({
                    type: "POST",
                    url: window.location.pathname + "/CreateLf",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify({ ordKeys: ordKeys, lfKey: lfName }),
                    async: false, cache: false,
                    success: function (data) {
                        lfName = data.d;
                    }
                });
                return false;
            }

            var changeAll = function () {
                ordKeys = [];
                var data = $('#<%=ctrlСтрокаЗаказа.ClientID%>').ajaxgroupedit('getDataRows');
                $('[id$=ctrlТовар]', data).each(
                    function () {
                        ordKeys.push($(this).val());
                    });
                changeLf();
                $('[id$=ctrlТовар]', data).each(
                    function () {
                        $(this).icsMasterEditorAjaxLookup('updateOptions', { lookup: { LFName: lfName } });
                    });
            };
			/**
				* Перебираем в АГЕ ctrlСтрокаЗаказа все лукапы ctrlТовар и проставляем им измененный limit function.
				*/
            if (ordKeys) {
                changeLf();
                $('[id$=ctrlТовар]', '#<%=ctrlСтрокаЗаказа.ClientID%>').each(
                    function () {
                        $(this).icsMasterEditorAjaxLookup('updateOptions', { lookup: { LFName: lfName } });
                    });
            }
			/**
				* Если в одном из лукапов ctrlТовар поменяли значение - то переопределяем все лукапы ctrlТовар в АГЕ ctrlСтрокаЗаказа.
				*/
            $( '#<%=ctrlСтрокаЗаказа.ClientID%>').on('change', '[id$=ctrlТовар]', function () {
                changeAll();
                autoCalc(this, this.parentNode.parentNode.parentNode.parentNode);
            });
			/**
				* Если добавлена новая строка в АГЕ, сразу назначим limit function.
				* @param {int} row Номер добавленной строки.
				*/
            $('#<%=ctrlСтрокаЗаказа.ClientID%>').on('rowadded.ajaxgroupedit', function (e, d) {
                $('[id$=ctrlТовар]', d).icsMasterEditorAjaxLookup('updateOptions', { lookup: { LFName: lfName } });
            });
			/**
				* Если удалена строка в АГЕ, сразу изменяем limit function.
				*/
            $('#<%=ctrlСтрокаЗаказа.ClientID%>').on('rowdeleted.ajaxgroupedit', function () {
                changeAll();
            });

            var autoCalc = function (_this, row) {
                var col = parseInt($('[id$=ctrlКоличество]', row).val());
                var price = parseFloat($('[id$=ctrlТовар_Цена]', row).text());
                price = price ? price : 0;
                var pricetax = 1.35 * price;
                $('[id$=ctrlЦенаСНалогами]', row).text(pricetax.toFixed(2));
                $('[id$=ctrlСумма]', row).text((col * pricetax).toFixed(2));
                var sum = 0;
                $('[id$=ctrlСумма]', '#<%=ctrlСтрокаЗаказа.ClientID%>').each(
                    function () {
                        sum += parseFloat($(this).text());
                    });

                $('#<%=ctrlЦена.ClientID%>').val(sum.toFixed(2));
            }

			/**
				* Вычисление цены и суммы.
				*/
            $('#<%=ctrlСтрокаЗаказа.ClientID%>').on('change', '[id$=ctrlКоличество]', function (e) {
                autoCalc(this, this.parentNode.parentNode.parentNode);
            });
        });

	</script>
</asp:Content>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass + " " +  Constants.EditFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass + " " + Constants.EditFormHeaderCssClass %>">Заказ</h2>
        <div class="<%= Constants.FormToolbarCssClass  + " " +  Constants.EditFormToolbarCssClass + " " + Constants.StickyCssClass %>">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="<%= Constants.FormControlsCssClass + " " + Constants.EditFormControlsCssClass %>">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlСтатусLabel" runat="server" Text="Статус" EnableViewState="False">
</asp:Label>
<asp:DropDownList ID="ctrlСтатус" CssClass="descTxt" runat="server">
	<asp:ListItem>Новый</asp:ListItem>
<asp:ListItem>Оплаченный</asp:ListItem>
<asp:ListItem>Отменённый</asp:ListItem>

</asp:DropDownList>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlДатаОтгрузкиLabel" runat="server" Text="Дата отгрузки" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlДатаОтгрузки" CssClass="descTxt" runat="server"/>
</div>
<ac:DatePickerValidator ID="ctrlДатаОтгрузкиDatePickerValidator" runat="server" ControlToValidate="ctrlДатаОтгрузки" 
                        ErrorMessage="Введена некорректная дата: Дата отгрузки." Text="*" 
                        EnableClientScript="true" ValidationGroup="savedoc" CssClass="validator-datePicker" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlДатаОплатыLabel" runat="server" Text="Дата оплаты" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlДатаОплаты" CssClass="descTxt" runat="server"/>
</div>
<ac:DatePickerValidator ID="ctrlДатаОплатыDatePickerValidator" runat="server" ControlToValidate="ctrlДатаОплаты" 
                        ErrorMessage="Введена некорректная дата: Дата оплаты." Text="*" 
                        EnableClientScript="true" ValidationGroup="savedoc" CssClass="validator-datePicker" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlЦенаLabel" runat="server" Text="Цена" EnableViewState="False">
</asp:Label>
<ac:DecimalTextBox runat="server" CssClass="descTxt" ID="ctrlЦена">
</ac:DecimalTextBox>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlНомерLabel" runat="server" Text="Номер" EnableViewState="False">
</asp:Label>
<ac:AlphaNumericTextBox CssClass="descTxt" ID="ctrlНомер" Type="Numeric" runat="server">
</ac:AlphaNumericTextBox>


</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlДатаЗаполненияLabel" runat="server" Text="Дата заполнения" EnableViewState="False">
</asp:Label>
<div class="descTxt">
    <ac:DatePicker ID="ctrlДатаЗаполнения" CssClass="descTxt" runat="server"/>
</div>
<ac:DatePickerValidator ID="ctrlДатаЗаполненияDatePickerValidator" runat="server" ControlToValidate="ctrlДатаЗаполнения" 
                        ErrorMessage="Введена некорректная дата: Дата заполнения." Text="*" 
                        EnableClientScript="true" ValidationGroup="savedoc" CssClass="validator-datePicker" />

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlМенеджерLabel" runat="server" Text="Менеджер" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlМенеджер" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlМенеджерRequiredFieldValidator" runat="server" ControlToValidate="ctrlМенеджер"
                            ErrorMessage="Не указано: Менеджер" Text="*" 
                            EnableClientScript="true" ValidationGroup="savedoc" />

</div>
<asp:ScriptManager ID="ScriptManager1" runat="server" >
</asp:ScriptManager>

<div style="clear: left">
	<ac:AjaxGroupEdit CssClass="$PERCENTMW$descTxt" ID="ctrlСтрокаЗаказа" runat="server" ReadOnly="false" />
</div>
<br/>

</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
